name: Update Domain Rule Count Badge Data

on:
  push:
    branches:
      - main
    # 只要脚本或配置变化都触发
    paths:
      - 'config.json'
      - 'count_rules.py'
      - '.github/workflows/update-badge.yml'
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug:list workspace
      run: |
        echo "Workspace: $GITHUB_WORKSPACE"
        ls -R .

    - name: Show script content
      run: head -n 30 count_rules.py

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run script to count rules and generate badge data
      run: python count_rules.py config.json

    - name: Deploy badge data to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: badge_data
        publish_branch: gh-pages
        title: 检查了一次当前仓库的规则数量
