name: Update Domain Rule Count Badge Data

on:
  push:
    branches:
      - main # 当 main 分支有新的 push 时触发
    paths:
      - 'config.json' # 当 config.json 有变化时触发
      - 'count_rules.py' # 当脚本有变化时触发
  schedule:
    - cron: '0 */2 * * *' # 每两小时更新一次 UTC 时间

  workflow_dispatch: # 允许手动触发 (可选)

permissions:
  contents: write # 只授予对仓库内容的写入权限
  
jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # <--- 移除步骤：安装 CJK 字体，现在由脚本自己下载字体 --->
    # - name: Install CJK fonts
    #   uses: RisingInIris2017/cjk-fonts-action@v1

    - name: Install dependencies # <--- 保持这个步骤，安装 requests 和 matplotlib 库 和 pytz 库
      run: |
        python -m pip install --upgrade pip
        pip install requests matplotlib numpy pytz

    - name: Run script to count rules, log history, and generate chart image # <--- 脚本会自己下载字体
      run: python count_rules.py config.json

    - name: Deploy badge data, history, and chart image to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # publish_dir 指向脚本输出的目录，现在包含了 badge json, history json 和 chart image
        publish_dir: badge_data # 这个目录名称和脚本中的一致
        publish_branch: gh-pages
        # cname: your-domain.com # 如果你的 GitHub Pages 使用了自定义域名，取消注释并替换
        # destination_dir: / # 默认就是发布到 gh-pages 分支的根目录
        title: Update domain rules count, history, and chart image # 修改 commit 标题
